config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"

  get "/sign_out" => "clearance/sessions#destroy", as: "sign_out"

  get "/sign_up" => "clearance/users#new", as: "sign_up"

  

  get 'welcome/index'

  root 'welcome#index'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  resources :users, only: [:show, :edit, :update, :destroy]

  resources :listings
  resources :application

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :user
	 mount_uploaders :images, ImagesUploader



end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

	def index
		@listing = Listing.all 
	end

	def show 
		@listing = Listing.find(params[:id])
	end


	def new
		@listing = Listing.new
		render template: "listings/new"

	end

	def create
		@listing = current_user.listings.new(listing_params)
		
		@listing.dates = (params[:listing][:start_date]..params[:listing][:end_date]).map(&:to_s)
		if @listing.save
	      flash[:success] = "Thank you for your listing"
	      redirect_to @listing
	    else
	      render template: "listings/new"
	    end
	end

	def edit
    	@listing = Listing.find(params[:id])

  	end

  def update
  	byebug
    @listing = Listing.find(params[:id])

    if @listing.update_attributes(listing_params)
    byebug
      redirect_to @listing

    else
      render 'edit'
    end
  end

  def destroy
    Listing.find(params[:id]).destroy
    flash[:success] = "Listing deleted"
    redirect_to listings_url
  end


	private

	def listing_params
		params.require(:listing).permit(:user_id, :name, :price, :address, :people, :amenities, :start_date, :end_date, {images:[]})
	end



end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing) do |form| %>
  

<div class="form-group" >
<label class="sr-only" for="exampleInputEmail2">Listing Name</label>
<%= form.text_field :name ,class:"form-control" ,id:"exampleInputEmail2", placeholder:"Listing Name" %>
</div>

<div class="form-group" >
<label class="sr-only" for="exampleInputEmail2">Price</label>
<%= form.number_field :price ,class:"form-control" ,id:"exampleInputEmail2", placeholder:"$ Price" %>
</div>

<div class="form-group">
<label class="sr-only" for="exampleInputPassword2"> Address</label>
<%= form.text_field :address, class:"form-control", id:"exampleInputPassword2", placeholder:"Address"%>
</div>

<div class="form-group" >
<label class="sr-only" for="exampleInputEmail2">Number of People</label>
<%= form.number_field :people ,class:"form-control" ,id:"exampleInputEmail2", placeholder:"How many people can stay?" %>
</div>

<div class="form-group" >
<label class="sr-only" for="exampleInputEmail2">Amenitites</label>
<%= form.text_field :amenities ,class:"form-control" ,id:"exampleInputEmail2", placeholder:" Amenities" %>
</div>
<div class="form-group" >
<label class="sr-only" for="exampleInputEmail2">Start Date</label>
<%= form.date_field :start_date ,class:"form-control" ,id:"exampleInputEmail2" %>
</div>

<div class="form-group" >
<label class="sr-only" for="exampleInputEmail2">End Date</label>
<%= form.date_field :end_date ,class:"form-control" ,id:"exampleInputEmail2" %>
</div>

<div class="submit-field">
<%= form.submit "Create Listing" %>
</div>




<% end %>

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>

<%= form_for(@listing) do |form| %>
  

<div class="form-group" >
<label class="sr-only" for="exampleInputEmail2">Listing Name</label>
 <b>Name: </b> <%= form.label  @listing.name %>
<%= form.text_field :name ,class:"form-control" ,id:"exampleInputEmail2", placeholder:"Listing Name" %>
</div>

<div class="form-group" >
<label class="sr-only" for="exampleInputEmail2">Price</label>
 <b>Price: </b> <%= (form.label @listing.price) if @listing.price? %>
<%= form.number_field :price ,class:"form-control" ,id:"exampleInputEmail2", placeholder:"$ Price" %>
</div>

<div class="form-group">
<b>Address: </b><%= form.label @listing.address %>
<label class="sr-only" for="exampleInputPassword2"> Address</label>
<%= form.text_field :address, class:"form-control", id:"exampleInputPassword2", placeholder:"Address"%>
</div>

<div class="form-group" >
<b>Number of People: </b><%= form.label @listing.people %>
<label class="sr-only" for="exampleInputEmail2">Number of People</label>
<%= form.number_field :people ,class:"form-control" ,id:"exampleInputEmail2", placeholder:"How many people can stay?" %>
</div>

<div class="form-group" >
<b>Amenities: </b><%= form.label @listing.amenities %>
<label class="sr-only" for="exampleInputEmail2">Amenities</label>
<%= form.text_field :amenities ,class:"form-control" ,id:"exampleInputEmail2", placeholder:" Amenities" %>
</div>

<div class="form-group" >
<b>Start Date: </b><%= form.label @listing.start_date %>
<label class="sr-only" for="exampleInputEmail2">Start Date</label>
<%= form.date_field :start_date ,class:"form-control" ,id:"exampleInputEmail2" %>
</div>

<div class="form-group" >
<b>End Date: </b><%= form.label @listing.end_date %>
<label class="sr-only" for="exampleInputEmail2">End Date</label>
<%= form.date_field :end_date ,class:"form-control" ,id:"exampleInputEmail2" %>
</div>

<div class="form-group">
<b>Pictures of your Accomodations: </b> 
<label class="sr-only" for="exampleInputPassword2"> Images</label>
<%= form.file_field :images, multiple: true, class:"form-control", id:"exampleInputPassword2", placeholder:"Upload Pictures" %>
</div>

<div class="submit-field">
<%= form.submit "Update Listing" %>
</div>




<% end %>

app/views/listings/index.html.erb
    
    <div class="container">

		<div class="row">

			<div class="[ col-xs-12 col-sm-offset-2 col-sm-8 ]">
			<button class="btn btn-info btn-lg btn-block"><%=link_to "Add New Listing", new_listing_path %></button>
						
				<ul class="event-list">

				
						
				
				<% Listing.all.each do |listing| %>
					<li>
						
						
						<time datetime="2014-07-20">
							<span class="day">$<%= listing.price if listing.price? %> </span>
					
						</time>
						<img alt="first picture"  <%= image_tag listing.images[0].url %> 
						
						<div class="info">
							<h2 class="title"><%= link_to listing.name, listing_path(listing.id) %></h2>
							<p class="desc"><%= listing.address %></p>
							<ul>
								<li style="width:33%;">Reviews <span class="glyphicon glyphicon-ok"></span></li>
								<li style="width:34%;">3 <span class="fa fa-question"></span></li>
								<li style="width:33%;">Availible <%=listing.people %><span class="fa fa-male"></span></li>
							</ul>
						</div>
						<% if current_user.id==(listing.user_id) %>
				
						<div class="social">
							<ul>
								<li class="google-plus"  style="width:33%;"><a class="btn">  <%= link_to "Edit", edit_listing_path(listing.id) %>   </li>
								<li class="google-plus"  style="width:34%;"><a  class="btn"> 
    							<%= link_to "delete", listing, method: :delete, data: { confirm: "You sure?"} %>


                                    </li>
							
								<li class="google-plus" style="width:33%;"><a href="#google-plus"><span class="fa fa-google-plus"></span></a></li>
							</ul>
						</div>
						<%end%>
					</li>
					<%end%>

			
				
			</div>
		</div>
	</div>

app/views/listings/new.html.erb
<% provide(:title, 'New Listing') %>

<div id="clearance" class="sign-in">
  <h2> New Listing </h2>

  <%= render partial: '/listings/form' %>

</div>

app/views/listings/show.html.erb
<div class="container">
    <div class="row">
                <div class="col-md-12 col-xs-12 col-sm-12">
                	<div class="artist-data pull-left">
                    	<div class="artst-pic pull-left">
                    		<!-- <span class="artst-like"><a href="#"><i class="glyphicon glyphicon-heart-empty"></i></a></span>
                    		<span class="artst-share"><a href="#"><i class="glyphicon glyphicon-share"></i></a></span>
                    		<span class="artst-plus"><a href="#"><i class="glyphicon glyphicon-plus-sign"></i></a></span> -->
                    		<a href="#">
                    			<img alt="" class="img-responsive" <%= image_tag @listing.images[0].url %>  
                    		</a>
                    	</div>
                        <div class="artst-prfle pull-right col-md-12 col-xs-12 col-sm-12">
                        	<div class="art-title">
                            	<%= @listing.name%>
                                <span class="artst-sub"> <span class="byname"><%= @listing.address%></span> 
                                 <span class="artst-sub"> <span class="byname"><%= @listing.amenities%></span>
                                 <span class="artst-sub"> <span class="byname"><%= @listing.people%></span>
                                <span class="daysago">5 Days Ago</span></span> 
                            </div>
                         <!--    <div class="counter-tab">
                            	<div class="counter_comnt"><i class="glyphicon glyphicon-comment"></i> 359</div>
                            	<div class="counter_ply"><i class="glyphicon glyphicon-play"></i> 1312</div>
                            	<div class="counter_like"><i class="glyphicon glyphicon-heart"></i> 2256</div>
                            </div> -->
                            <% if current_user.id==(@listing.user_id) %>
                            <div class="btn"><i class="icon-edit"></i> <strong><%= link_to "Edit", edit_listing_path(@listing.id) %> </strong></div>
                            <a href="#" class="btn"><i class="icon-trash"></i> <strong> <%= link_to "delete", @listing, method: :delete, data: { confirm: "You sure?"} %>
                                    </strong></a>
                            
                            <%end%>
                            <a href="#" class="btn"><i class="icon-align-justify"></i> <strong> <%= link_to "All Listings", listings_path %> </strong></a>
                        </div>
                        <div class="bot-links">
                        	<a href="#">Sit amet</a>
                        	<a href="#">Amet</a>
                        </div>
                    </div>

                 </div>
                        
               
                
            </div>
</div>