config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"

  get "/sign_out" => "clearance/sessions#destroy", as: "sign_out"

  get "/sign_up" => "clearance/users#new", as: "sign_up"

  

  get 'welcome/index'

  root 'welcome#index'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  resources :users, only: [:show, :edit, :update, :destroy]

  resources :listings
  resources :application

end

app/models/user.rb
class User <  ActiveRecord::Base
  include Clearance::User
   has_many :authentications, :dependent => :destroy
   has_many :listings
   mount_uploader :avatar, AvatarUploader

  def self.create_with_auth_and_hash(authentication,auth_hash)
  	
    create! do |u|
     u.first_name = auth_hash["info"]["first_name"]
     u.last_name = auth_hash["info"]["last_name"]
     
     u.image = auth_hash["info"]["image"]
     u.email = auth_hash["extra"]["raw_info"]["email"]
     u.password = [*('A'..'Z')].sample(8).join
     u.authentications<<(authentication)
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end




end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < ApplicationController
 if respond_to?(:before_action)
   before_action :redirect_signed_in_users, only: [:create, :new]
   skip_before_action :require_login, only: [:create, :new], raise: false
   skip_before_action :authorize, only: [:create, :new], raise: false
 else
   before_filter :redirect_signed_in_users, only: [:create, :new]
   skip_before_filter :require_login, only: [:create, :new], raise: false
   skip_before_filter :authorize, only: [:create, :new], raise: false
 end

 def new
   @user = user_from_params
   render template: "users/new"
 end

 def create
   @user = user_from_params

   if @user.save
     sign_in @user
     redirect_back_or url_after_create
   else
     render template: "users/new"
   end
 end

 private

 def avoid_sign_in
   warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
     "deprecated. Use `redirect_signed_in_users` instead. " +
     "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
     " or `skip_before_action :avoid_sign_in` as well"
   redirect_signed_in_users
 end

 def redirect_signed_in_users
   if signed_in?
     redirect_to Clearance.configuration.redirect_url
   end
 end

 def url_after_create
   Clearance.configuration.redirect_url
 end

 def user_from_params

   email = user_params.delete(:email)
   password = user_params.delete(:password)
   first_name = user_params.delete(:first_name)
   last_name = user_params.delete(:last_name)
  

   Clearance.configuration.user_model.new(user_params).tap do |user|
     user.email = email
     user.password = password
     user.first_name = first_name
     user.last_name = last_name
   
   end
 end

 def user_params
   params[Clearance.configuration.user_parameter] || Hash.new
 end


 def show 
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show 
    @user = User.find(params[:id])
  	end
	
	def edit
	@user = User.find(params[:id])
  	end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(the_user_params)
      redirect_to @user

    else
      render 'edit'
    end
  end




	private

	def the_user_params
		params.require(:user).permit(:first_name, :last_name, :email, :avatar)
	end


 end



#    def user_from_params
#     byebug
#     email = user_params.delete(:email)
#     password = user_params.delete(:password)
#     first_name = user_params.delete(:first_name)
#    #  last_name = user_params.delete(:last_name)
#    # birthday = user_params.delete(:birthday)
#       Clearance.configuration.user_model.new(user_params).tap do |user|
#         user.email = email
#           user.password = password
#             user.first_name = first_name
#             # user.last_name = last_name
#             # user.date_of_birth = date_of_birth
#             # user.subscribe = subscribe
#        end
#     # params.require(:user).permit(:email, :password, :first_name)
#     end
  
#   def create
#     @user = User.new(user_from_params)
#     byebug
#     if @user.save
#       sign_in @user
#       redirect_back_or url_after_create
#     else
#       render template: "users/new"
#     end
#   end




#   #   def user_params
#   #      param.require(:user).permit(:email, :first_name, :password)
#   # end



#   end


# end

# class Clearance::UsersController < ApplicationController
#  if respond_to?(:before_action)
#    before_action :redirect_signed_in_users, only: [:create, :new]
#    skip_before_action :require_login, only: [:create, :new], raise: false
#    skip_before_action :authorize, only: [:create, :new], raise: false
#  else
#    before_filter :redirect_signed_in_users, only: [:create, :new]
#    skip_before_filter :require_login, only: [:create, :new], raise: false
#    skip_before_filter :authorize, only: [:create, :new], raise: false
#  end

#  def new
#    @user = user_from_params
#    render template: "users/new"
#  end

#  def create
#    @user = user_from_params

#    if @user.save
#      sign_in @user
#      redirect_back_or url_after_create
#    else
#      render template: "users/new"
#    end
#  end

#  private

#  def avoid_sign_in
#    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
#      "deprecated. Use `redirect_signed_in_users` instead. " +
#      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
#      " or `skip_before_action :avoid_sign_in` as well"
#    redirect_signed_in_users
#  end

#  def redirect_signed_in_users
#    if signed_in?
#      redirect_to Clearance.configuration.redirect_url
#    end
#  end

#  def url_after_create
#    Clearance.configuration.redirect_url
#  end

#  def user_from_params

#    email = user_params.delete(:email)
#    password = user_params.delete(:password)
#    first_name = user_params.delete(:first_name)
#    last_name = user_params.delete(:last_name)
#    date_of_birth = user_params.delete(:date_of_birth)
#    subscribe = user_params.delete(:subscribe)

#    Clearance.configuration.user_model.new(user_params).tap do |user|
#      user.email = email
#      user.password = password
#      user.first_name = first_name
#      user.last_name = last_name
#      user.date_of_birth = date_of_birth
#      user.subscribe = subscribe
#    end
#  end

#  # def user_params
#  #   params[Clearance.configuration.user_parameter] || Hash.new
#  # end

#  def user_params
#     params.require(:user).permit(:first_name,:last_name :email, :password, :birthday, :encrypted_password)
#      params[Clearance.configuration.user_parameter] || Hash.new
#   end
# end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>

 
</div>

<div class="text-field">

  <%= form.label :first_name %>
  <%= form.text_field :first_name %>
</div>

<div class="text-field">

  <%= form.label :last_name %>
  <%= form.text_field :last_name %>
</div>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= form_for(@user) do |form| %>
  

<div class="form-group" >
<label class="sr-only" for="exampleInputEmail2">First Name</label>
 <b>First: </b> <%= form.label  @user.first_name %>
<%= form.text_field :first_name ,class:"form-control" ,id:"exampleInputEmail2", placeholder:"First Name" %>
</div>

<div class="form-group" >
<label class="sr-only" for="exampleInputEmail2">Last Name</label>
 <b>Last: </b> <%= (form.label @user.last_name) %>
<%= form.text_field :last_name ,class:"form-control" ,id:"exampleInputEmail2", placeholder:"Last Name" %>
</div>

<div class="form-group">
<b>Email: </b> 
<label class="sr-only" for="exampleInputPassword2"> Email</label>
<%= form.text_field :email, class:"form-control", id:"exampleInputPassword2", placeholder:"Email"%>
</div>

<div class="form-group">
<b>Avatar Picture: </b> 
<label class="sr-only" for="exampleInputPassword2"> Avatar</label>
<%= form.file_field :avatar, class:"form-control", id:"exampleInputPassword2", placeholder:"Upload a Picture"%>
</div>

<div class="submit-field">
<%= form.submit "Update Profile" %>
</div>




<% end %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
	<div class="row">
		<div class="col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
    	 <div class="well profile">
            <div class="col-sm-12">
                <div class="col-xs-12 col-sm-8">
                    <h2><%=@user.first_name %> 
                    <%= @user.last_name %></h2>
                    <p><strong>Email: </strong> <%=@user.email %> </p>
                    <p><strong>Hobbies: </strong> Read, out with friends, listen to music, draw and learn new things. </p>
                    <p><strong>Skills: </strong>
                        <span class="tags">html5</span> 
                        <span class="tags">css3</span>
                        <span class="tags">jquery</span>
                        <span class="tags">bootstrap3</span>
                    </p>
                </div>             
                <div class="col-xs-12 col-sm-4 text-center">
                    <figure>
                        <img src= <%= @user.avatar_url.to_s %> alt="" class="img-circle img-responsive">


                        <figcaption class="ratings">
                            <p>Ratings
                            <a href="#">
                                <span class="fa fa-star"></span>
                            </a>
                            <a href="#">
                                <span class="fa fa-star"></span>
                            </a>
                            <a href="#">
                                <span class="fa fa-star"></span>
                            </a>
                            <a href="#">
                                <span class="fa fa-star"></span>
                            </a>
                            <a href="#">
                                 <span class="fa fa-star-o"></span>
                            </a> 
                            </p>
                        </figcaption>
                    </figure>
                </div>
            </div>            
            <div class="col-xs-12 divider text-center">
                <div class="col-xs-12 col-sm-4 emphasis">                  
                    <div class="btn"><i class="icon-edit"></i> <strong><%= link_to "Edit", edit_user_path(@user.id) %></strong></div>
                </div>
                <div class="col-xs-12 col-sm-4 emphasis">                  
                    <div href="#" class="btn"><i class="icon-trash"></i> <strong><%= link_to "Delete", @user, method: :delete, data: { confirm: "You sure?"} %></strong></div>
                </div>
















            </div>
    	 </div>                 
		</div>
	</div>
</div>